Repository MasterTeamFTN/uks, pull requests merged in 2021-01, with the labels that each got.

#5 Feature/login-logout
  app/templates/app/base.html
  uks/settings.py
  uks/urls.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/templates/users/login.html
  users/templates/users/logout.html
  users/tests.py
  users/urls.py
  users/views.py
Labels: new feature

#12 Feature/projects
  app/admin.py
  app/migrations/0001_initial.py
  app/migrations/0002_project_contributors.py
  app/models.py
  app/static/app/main.css
  app/templates/app/base.html
  app/templates/app/home.html
  app/templates/app/project_confirm_delete.html
  app/templates/app/project_detail.html
  app/templates/app/project_form.html
  app/templates/app/projects.html
  app/urls.py
  app/views.py
  package-lock.json
Labels: new feature

#14 Feature/wikis
  app/admin.py
  app/migrations/0001_initial.py
  app/migrations/0002_project_contributors.py
  app/migrations/__init__.py
  app/models.py
  app/templates/app/project_detail.html
  app/templates/app/wiki_confirm_delete.html
  app/templates/app/wiki_detail.html
  app/templates/app/wiki_form.html
  app/templates/app/wiki_list.html
  app/templates/app/wikiversion_list.html
  app/urls.py
  app/views.py
  requirements.txt
  uks/settings.py
Labels: new feature

#21 App structure refactoring
  app/admin.py
  app/labels/__init__.py
  app/labels/models.py
  app/labels/urls.py
  app/labels/views.py
  app/models.py
  app/projects/__init__.py
  app/projects/models.py
  app/projects/urls.py
  app/projects/views.py
  app/urls.py
  app/views.py
  app/wikis/__init__.py
  app/wikis/models.py
  app/wikis/urls.py
  app/wikis/views.py
Labels: refactor

#27 Contributors page
  app/projects/urls.py
  app/projects/views.py
  app/templates/app/project/contributors.html
  app/templates/app/project/project_detail.html
Labels: new feature, refactor

#29 Feature/milestones
  app/admin.py
  app/labels/views.py
  app/migrations/0004_milestone.py
  app/migrations/0005_auto_20210113_2105.py
  app/migrations/0006_auto_20210113_2106.py
  app/milestones/__init__.py
  app/milestones/models.py
  app/milestones/urls.py
  app/milestones/views.py
  app/models.py
  app/templates/app/base.html
  app/templates/app/label/label_list.html
  app/templates/app/milestone/milestone_confirm_delete.html
  app/templates/app/milestone/milestone_detail.html
  app/templates/app/milestone/milestone_form.html
  app/templates/app/milestone/milestone_list.html
  app/templates/app/project/project_detail.html
  app/urls.py
  requirements.txt
  uks/settings.py
  users/admin.py
  users/apps.py
  users/forms.py
  users/migrations/0001_initial.py
  users/models.py
  users/signals.py
  users/templates/users/profile.html
  users/urls.py
  users/views.py
Labels: new feature

#28 Profile, edit profile and change photo implemented
  app/templates/app/base.html
  app/urls.py
  requirements.txt
  uks/settings.py
  users/admin.py
  users/apps.py
  users/forms.py
  users/migrations/0001_initial.py
  users/models.py
  users/signals.py
  users/templates/users/profile.html
  users/urls.py
  users/views.py
Labels: new feature

#30 'feature/profile'
  app/templates/app/base.html
  users/templates/users/edit_profile.html
  users/templates/users/profile_details.html
  users/urls.py
  users/views.py
Labels: new feature

#31 Feature/organizations
  app/admin.py
  app/migrations/0007_organization.py
  app/migrations/0008_organization_members.py
  app/models.py
  app/organizations/__init__.py
  app/organizations/models.py
  app/organizations/urls.py
  app/organizations/views.py
  app/templates/app/base.html
  app/templates/app/organization/add_member.html
  app/templates/app/organization/organization_confirm_delete.html
  app/templates/app/organization/organization_detail.html
  app/templates/app/organization/organization_form.html
  app/templates/app/organization/organization_list_all.html
  app/templates/app/organization/organization_update.html
  app/urls.py
  uks/settings.py
Labels: new feature

#32 Fix/labels
  app/labels/views.py
  app/templates/app/label/label_list.html
Labels: fix

#38 feature/predefined-labels
  app/apps.py
  app/projects/signals.py
  app/utils/__init__.py
  app/utils/default_labels.py
Labels: new feature

#40 Feature/tasks
  app/migrations/0007_task_taskversion.py
  app/migrations/0008_task_milestone.py
  app/migrations/0009_taskversion_taskstate.py
  app/migrations/0010_auto_20210118_1245.py
  app/migrations/0011_auto_20210118_1248.py
  app/migrations/0012_auto_20210118_1249.py
  app/migrations/0013_auto_20210118_1257.py
  app/tasks/__init__.py
  app/tasks/models.py
  app/tasks/urls.py
  app/tasks/views.py
  app/templates/app/base.html
  app/templates/app/project/project_detail.html
  app/templates/app/task/task_details.html
  app/templates/app/task/task_form.html
  app/templates/app/task/task_list.html
  app/templates/app/task/user_task_list.html
  app/templates/app/wiki/wiki_detail.html
  app/urls.py
  uks/settings.py
Labels: new feature

#45 Feature/milestone tasks
  app/milestones/urls.py
  app/milestones/views.py
  app/templates/app/milestone/milestone_detail.html
  app/templates/app/milestone/milestone_list.html
Labels: new feature

#48 Update label bag
  app/labels/views.py
  app/projects/views.py
Labels: fix

#51 Feature/commits
  app/migrations/0014_merge_20210118_1822.py
  app/migrations/0015_project_github_url.py
  app/migrations/0016_branch.py
  app/migrations/0017_commit.py
  app/projects/models.py
  app/projects/signals.py
  app/projects/urls.py
  app/projects/views.py
  app/templates/app/project/branches.html
  app/templates/app/project/commits.html
  app/templates/app/project/project_detail.html
  app/utils/github_utils.py
Labels: new feature
