Repository MasterTeamFTN/uks, pull requests merged in 2021-02, with the labels that each got.

#47 Feature/comments
  app/migrations/0014_merge_20210118_1856.py
  app/migrations/0015_comment.py
  app/migrations/0016_changehistory.py
  app/tasks/models.py
  app/tasks/urls.py
  app/tasks/views.py
  app/templates/app/task/comment_form.html
  app/templates/app/task/task_details.html
Labels: new feature

#52 fix/crud-authorizations
  app/templates/app/label/label_list.html
  app/templates/app/milestone/milestone_detail.html
  app/templates/app/milestone/milestone_list.html
  app/templates/app/task/board.html
  app/templates/app/task/task_details.html
  app/templates/app/task/task_list.html
  app/templates/app/wiki/wiki_detail.html
  app/templates/app/wiki/wiki_list.html
  app/templates/app/wiki/wikiversion_list.html
Labels: fix

#56 Feature/dev ops
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/uks.iml
  .idea/vcs.xml
  Dockerfile
  app/migrations/0001_initial.py
  app/migrations/0002_remove_label_color.py
  app/migrations/0003_label_color.py
  app/migrations/0004_milestone.py
  app/migrations/0005_auto_20210113_2105.py
  app/migrations/0006_auto_20210113_2106.py
  app/migrations/0007_organization.py
  app/migrations/0007_task_taskversion.py
  app/migrations/0008_organization_members.py
  app/migrations/0008_task_milestone.py
  app/migrations/0009_taskversion_taskstate.py
  app/migrations/0010_auto_20210118_1245.py
  app/migrations/0011_auto_20210118_1248.py
  app/migrations/0012_auto_20210118_1249.py
  app/migrations/0013_auto_20210118_1257.py
  config/logstash/logstash.conf
  config/nginx/nginx.conf
  config/telegraf/telegraf.conf
  datadump.json
  docker-compose.yml
  posgreDump.json
  requirements.txt
  uks/settings.py
  users/migrations/0001_initial.py
Labels: devops

#62 Feature/travis
  .travis.yml
Labels: devops

#57 Created tests for wiki pages
  .gitignore
  .travis.yml
  Makefile
  app/migrations/0001_initial.py
  app/migrations/0014_merge_20210118_1822.py
  app/migrations/0014_merge_20210118_1856.py
  app/migrations/0015_comment.py
  app/migrations/0015_project_github_url.py
  app/migrations/0016_branch.py
  app/migrations/0016_changehistory.py
  app/migrations/0017_commit.py
  app/utils/github_utils.py
  app/wikis/tests/__init__.py
  app/wikis/tests/test_models.py
  app/wikis/tests/test_urls.py
  app/wikis/tests/test_views.py
  app/wikis/views.py
  media/default.jpg
  uks/settings.py
Labels: testing

#59 Error pages created
  app/templates/400.html
  app/templates/403.html
  app/templates/404.html
  app/templates/500.html
  app/urls.py
  app/views.py
Labels: technical

#65 Feature/add remove contributors
  app/projects/signals.py
  app/projects/urls.py
  app/projects/views.py
  app/templates/app/project/add_member.html
  app/templates/app/project/contributors.html
Labels: new feature, refactor

#68 Project settings page
  app/projects/urls.py
  app/projects/views.py
  app/templates/app/home.html
  app/templates/app/project/project_detail.html
  app/templates/app/project/project_edit.html
  app/templates/app/project/settings.html
Labels: new feature

#69 Feature/statistics
  app/projects/urls.py
  app/projects/views.py
  app/tasks/models.py
  app/templates/app/milestone/milestone_detail.html
  app/templates/app/project/project_detail.html
  app/templates/app/project/statistics_pulse.html
  app/templates/app/task/board.html
  app/templates/app/task/task_list.html
Labels: new feature

#70 Feature/all projects page
  app/projects/urls.py
  app/projects/views.py
  app/templates/app/base.html
  app/templates/app/project/projects.html
Labels: new feature, refactor

#75 Feature/add projects to organizations
  app/migrations/0002_project_organization.py
  app/organizations/urls.py
  app/organizations/views.py
  app/projects/models.py
  app/static/app/main.css
  app/templates/app/organization/organization_detail.html
Labels: new feature

#76 user profile statistic created
  app/migrations/0001_initial.py
  app/migrations/0002_project_organization.py
  users/migrations/0001_initial.py
  users/templates/users/profile_details.html
  users/views.py
Labels: new feature

#77 done label testing
  app/labels/tests/__init__.py
  app/labels/tests/test_models.py
  app/labels/tests/test_urls.py
  app/labels/tests/test_views.py
  app/labels/views.py
  app/templates/app/base.html
  app/templates/app/organization/organization_detail.html
  app/templates/app/project/commits.html
  app/templates/app/project/contributors.html
  app/templates/app/wiki/wikiversion_list.html
  users/templates/users/profile_details.html
  users/templates/users/user_profile.html
  users/urls.py
  users/views.py
Labels: testing

#78 Updated model
  diagrams/UKS.oom
  diagrams/UKS.pdf
Labels: documentation, technical

#79 fix/tasks
  app/tasks/forms.py
  app/tasks/models.py
  app/tasks/views.py
Labels: fix

#80 Milestone tests added
  app/labels/views.py
  app/milestones/tests/__init__.py
  app/milestones/tests/test_models.py
  app/milestones/tests/test_urls.py
  app/milestones/tests/test_views.py
  app/milestones/views.py
Labels: testing

#81 Feature/pulse
  app/migrations/0001_initial.py
  app/projects/urls.py
  app/projects/views.py
  app/templates/app/base.html
  app/templates/app/project/statistics_pulse.html
  package-lock.json
Labels: new feature
